name: Delete old workflow runs
on:
  schedule:
    - cron: '0 15 * * *' # 日本時間の毎日0:00に自動実行
  workflow_dispatch: # 画面から手動で実行するボタンも表示させる

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0           # 日数での指定は無効化（0日）
          keep_minimum_runs: 80   # ★最新の100件だけを残す

          name: Delete old workflow runs
