name: Option Data

on:
  schedule:
    - cron: "16 21 * * *"  # 🇯🇵 日本時間の 朝6:16 に自動実行
    - cron: "16 7 * * *"   # 🇯🇵 日本時間の 夕方16:16 に自動実行
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install selenium pandas openpyxl webdriver-manager lxml

      - name: Run script
        run: python Get_Option_Data.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: option-data
          path: Get_Option_Data_*.xlsx
