name: Run Option Data

on:
  schedule:
    - cron: '0 22 * * *'
    - cron: '0 7 * * *'

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install packages
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: |
          python Get_Option_Data.py

      - name: Upload Excel
        uses: actions/upload-artifact@v4
        with:
          name: option-data
          path: "*.xlsx"
